
    function myKeyword(){

    $("#role" ).autocomplete({
        source: function( request, response ) {
            console.log("req: " + JSON.stringify(request));
            console.log("re: " + JSON.stringify(response));
          $.ajax({
            url: "/keywordAutocomplete.php",
            dataType: "jsonp",
            data: {
                name_startsWith: request.term
            },
            success: function( data ) {
                console.log(JSON.stringify(data));
                response( $.map( data.keyword, function( item ) {

                    return {
                        label:item,
                        value: item
                    }
                }).splice(0,12));
            }
        });
    },
    minLength: 0,
    select: function( event, ui ) {
        logkey( ui.item ? ui.item.label : this.value);
    },
    open: function() {
        $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
    },
    close: function() {
        $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
    }
  });
 }
    function myAutoComplete(country){

    $("#location" ).autocomplete({
        source: function( request, response ) {
            console.log("req: " + JSON.stringify(request));
            console.log("re: " + JSON.stringify(response));
          $.ajax({
            url: "/cityAutocompletion.php",
            dataType: "jsonp",
            data: {
                featureClass: "P",
                style: "full",
                maxRows: 12,
                country:country,
                name_startsWith: request.term
            },
            success: function( data ) {
                console.log(JSON.stringify(data));
                response( $.map( data.City_Info, function( item ) {

                    return {
                        label:item.City_State,
                        value: item.City_State
                    }
                }).splice(0,12));
            }
        });
    },
    minLength: 0,
    select: function( event, ui ) {
        logloc( ui.item ? ui.item.label : this.value);
    },
    open: function() {
        $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
    },
    close: function() {
        $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
    }
  });
 }

    function logkey( message ) {
        $("#role").val(message);
    }
    function logloc( message ) {
        $("#location").val(message);
    }
    function ClosePopUp(){
        $("#err").modal('hide');
    }
var citiesJSON=[
    "Ottawa, ON",
    "Victoria, BC",
    "Toronto, ON",
    "Parksville, BC",
    "Edmonton, AB",
    "Vancouver, BC",
    "Saskatoon, SK",
    "London, ON",
    "Halifax, NS",
    "Calgary, AB",
    "Varennes, QC",
    "Fredericton, NB",
    "Athabasca, AB",
    "Dorval, QC",
    "Montreal, QC",
    "Quebec, QC",
    "Trois-rivières, QC",
    "Sherbrooke, QC",
    "Chicoutimi, QC",
    "Winnipeg, MB",
    "Lloydminster, AB",
    "Airdrie, AB",
    "Nanaimo, BC",
    "Duncan, BC",
    "Leduc, AB",
    "Nisku, AB",
    "Orillia, ON",
    "Barrie, ON",
    "Alliston, ON",
    "Edmundston, NB",
    "Mississauga, ON",
    "Charlesbourg, QC",
    "Burnaby, BC",
    "Scarborough, ON",
    "Oakville, ON",
    "Kanata, ON",
    "Lethbridge, AB",
    "Charlottetown, PE",
    "Regina, SK",
    "Brampton, ON",
    "Etobicoke, ON",
    "Windsor, ON",
    "Whitby, ON",
    "Oshawa, ON",
    "Kitchener, ON",
    "Kamloops, BC",
    "Rexdale, ON",
    "Laval, QC",
    "Downsview, ON",
    "Moncton, NB",
    "Côte-saint-luc, QC",
    "Lachine, QC",
    "Lévis, QC",
    "Mont-joli, QC",
    "Welland, ON",
    "Timmins, ON",
    "Langley, BC",
    "Markham, ON",
    "Saint-laurent, QC",
    "Nepean, ON",
    "Ancaster, ON",
    "Guelph, ON",
    "Hamilton, ON",
    "Abbotsford, BC",
    "Eriksdale, MB",
    "Pinawa, MB",
    "Minnedosa, MB",
    "Winkler, MB",
    "Kelligrews, NL",
    "Summerside, PE",
    "Sainte-foy, QC",
    "Valcourt, QC",
    "Roberval, QC",
    "Orangeville, ON",
    "Drummondville, QC",
    "Gravenhurst, ON",
    "Joliette, QC",
    "Ajax, ON",
    "Cranbrook, BC",
    "Thornhill, ON",
    "Newmarket, ON",
    "Chesley, ON",
    "Bonnyville, AB",
    "Gatineau, QC",
    "Barrhead, AB",
    "Sudbury, ON",
    "Drumheller, AB",
    "Hearst, ON",
    "Brantford, ON",
    "Longueuil, QC",
    "Beaconsfield, QC",
    "Pierrefonds, QC",
    "Magog, QC",
    "Châteauguay, QC",
    "Saint-eustache, QC",
    "Brockville, ON",
    "Stratford, ON",
    "Milton, ON",
    "Strathroy, ON",
    "Sarnia, ON",
    "Belleville, ON",
    "Stouffville, ON",
    "Beloeil, QC",
    "Maniwaki, QC",
    "Anjou, QC",
    "Sainte-thérèse, QC",
    "Mont-royal, QC",
    "Brossard, QC",
    "Montréal-nord, QC",
    "Terrebonne, QC",
    "Alma, QC",
    "Kingston, ON",
    "Arnprior, ON",
    "Jonquière, QC",
    "Victoriaville, QC",
    "Thorold, ON",
    "Lindsay, ON",
    "Pickering, ON",
    "Campbellford, ON",
    "Meaford, ON",
    "Saint-hubert, QC",
    "Chomedey, QC",
    "Beauport, QC",
    "Outremont, QC",
    "Matane, QC",
    "Boucherville, QC",
    "Lavaltrie, QC",
    "Niagara, ON",
    "Valleyfield, QC",
    "Candiac, QC",
    "Mont-tremblant, QC",
    "Rivière-du-loup, QC",
    "Granby, QC",
    "Pointe-claire, QC",
    "Saint-jérôme, QC",
    "Cowansville, QC",
    "Whitehorse, YT",
    "Yellowknife, NT",
    "Inuvik, NT",
    "Leamington, ON",
    "Coquitlam, BC",
    "Castlegar, BC",
    "Surrey, BC",
    "Beamsville, ON",
    "Hagersville, ON",
    "Montréal-est, QC",
    "Delta, BC",
    "Baie-d'urfe, QC",
    "Bowmanville, ON",
    "Stittsville, ON",
    "Bamfield, BC",
    "Napanee, ON",
    "Terrace, BC",
    "Edson, AB",
    "Banff, AB",
    "Ponoka, AB",
    "Smithers, BC",
    "Dryden, ON",
    "Eganville, ON",
    "Vanderhoof, BC",
    "Tofino, BC",
    "Aylmer, QC",
    "Kelowna, BC",
    "Lennoxville, QC",
    "Turtleford, SK",
    "Caronport, SK",
    "Lampman, SK",
    "Melfort, SK",
    "Yorkton, SK",
    "Repentigny, QC",
    "Weyburn, SK",
    "Ridgetown, ON",
    "Quesnel, BC",
    "Westmount, QC",
    "Rossport, ON",
    "Penticton, BC",
    "Sept-Îles, QC",
    "Courtenay, BC",
    "Ashcroft, BC",
    "Chilliwack, BC",
    "Brackendale, BC",
    "Vernon, BC",
    "Hawkesbury, ON",
    "Cobourg, ON",
    "Tecumseh, ON",
    "Haliburton, ON",
    "Dollard-des-ormeaux, QC",
    "Lachute, QC",
    "Courtright, ON",
    "Sorel, QC",
    "Blainville, QC",
    "Île-perrot, QC",
    "Walkerton, ON",
    "L'orignal, ON",
    "Renfrew, ON",
    "Ingersoll, ON",
    "Collingwood, ON",
    "Saint-rémi, QC",
    "Saint-hyacinthe, QC",
    "Val-d'or, QC",
    "Wetaskiwin, AB",
    "Hinton, AB",
    "Didsbury, AB",
    "Comox, BC",
    "Rimouski, QC",
    "Thessalon, ON",
    "Deux-montagnes, QC",
    "Penetanguishene, ON",
    "Vaudreuil, QC",
    "Lyster, QC",
    "Whitchurch-stouffville, ON",
    "Kindersley, SK",
    "Bécancour, QC",
    "Ormstown, QC",
    "Sombra, ON",
    "Edam, SK",
    "Virden, MB",
    "Assiniboia, SK",
    "Saint-stanislas-de-kostka, QC",
    "Mirabel, QC",
    "Salaberry-de-valleyfield, QC",
    "Caledon, ON",
    "Macgregor, MB",
    "Atikokan, ON",
    "Tillsonburg, ON",
    "Estevan, SK",
    "Sillery, QC",
    "Pointe-aux-trembles, QC",
    "Sainte-agathe, QC",
    "Valemount, BC",
    "Hixon, BC",
    "Ladner, BC",
    "Tsawwassen, BC",
    "Kemptville, ON",
    "Petawawa, ON",
    "Iroquois, ON",
    "Deline, NT",
    "Tulita, NT",
    "Paulatuk, NT",
    "Tuktoyaktuk, NT",
    "Tsiigehtchic, NT",
    "Saint-michel-des-saints, QC",
    "Saint-bruno-de-montarville, QC",
    "Laprairie, QC",
    "Beauharnois, QC",
    "Wainwright, AB",
    "Ile-à-la-crosse, SK",
    "Beachburg, ON",
    "Ladysmith, BC",
    "Longlac, ON",
    "Schreiber, ON",
    "Tavistock, ON",
    "Whitecourt, AB",
    "Sackville, NB",
    "Rosemère, QC",
    "Donnacona, QC",
    "Courtice, ON",
    "Englehart, ON",
    "Coaticook, QC",
    "Abbottsford, BC",
    "Cap-de-la-madeleine, QC",
    "Mcmasterville, QC",
    "Shawville, QC",
    "Calabogie, ON",
    "Shawinigan, QC",
    "Baie-saint-paul, QC",
    "Niagara-on-the-lake, ON",
    "Dunnville, ON",
    "Tilsonburg, ON",
    "Amherstburg, ON",
    "Bracebridge, ON",
    "Dorion, QC",
    "Gananoque, ON",
    "Rigaud, QC",
    "Fabreville, QC",
    "Lacolle, QC",
    "Stayner, ON",
    "Rivière-des-prairies, QC",
    "Dolbeau, QC",
    "Saint-félicien, QC",
    "Plessisville, QC",
    "Laval-des-rapides, QC",
    "Deseronto, ON",
    "Madoc, ON",
    "Waterdown, ON",
    "Onoway, AB",
    "Streetsville, ON",
    "Pont-rouge, QC",
    "Chapleau, ON",
    "Michipicoten, ON",
    "Sainte-cécile-de-masham, QC",
    "Grenville, QC",
    "Canmore, AB",
    "Cardston, AB",
    "Normandin, QC",
    "Camrose, AB",
    "Kitscoty, AB",
    "Hobbema, AB",
    "Morinville, AB",
    "Kinuso, AB",
    "Pont-viau, QC",
    "Simcoe, ON",
    "Saint-agapit, QC",
    "Sainte-adèle, QC",
    "Gaspé, QC",
    "Baie-comeau, QC",
    "Asbestos, QC",
    "Saint-germain-de-grantham, QC",
    "Crabtree, QC",
    "Chute-aux-outardes, QC",
    "Wolfville, NS",
    "Kentville, NS",
    "Carbonear, NL",
    "Whitbourne, NL",
    "Twillingate, NL",
    "Dildo, NL",
    "Fergus, ON",
    "Fonthill, ON",
    "Queenston, ON",
    "Marieville, QC",
    "Jacques-cartier, QC",
    "Verchères, QC",
    "Saint-pie, QC",
    "Saint-jean-eudes, QC",
    "Sainte-thérèse-de-blainville, QC",
    "Laurentides, QC",
    "Saint-jean, QC",
    "Saint-augustin, QC",
    "Mcwatters, QC",
    "Cléricy, QC",
    "Senneville, QC",
    "Dubuisson, QC",
    "Senneterre, QC",
    "Palmarolle, QC",
    "Hantsport, NS",
    "Hébertville, QC",
    "Sainte-julienne, QC",
    "Shawinigan-sud, QC",
    "Saint-sauveur-des-monts, QC",
    "Chesterville, ON",
    "Kitimat, BC",
    "Omemee, ON",
    "Pincourt, QC",
    "Charlemagne, QC",
    "Portneuf, QC",
    "Westlock, AB",
    "Redcliff, AB",
    "Fernie, BC",
    "Invermere, BC",
    "Wasa, BC",
    "Creston, BC",
    "Squamish, BC",
    "Garibaldi, BC",
    "Ioco, BC",
    "Colborne, ON",
    "Balzac, AB",
    "Parkbeg, SK",
    "Wilkie, SK",
    "Searchmont, ON",
    "Skidegate, BC",
    "Sandspit, BC",
    "Chemainus, BC",
    "Kuujjuaq, QC",
    "Livelong, SK",
    "Shaunavon, SK",
    "Sanikiluaq, NU",
    "Igloolik, NU",
    "Holman, NT",
    "Hornepayne, ON",
    "Cochrane, ON",
    "Moosonee, ON",
    "Slocan, BC",
    "Arviat, NU",
    "Iqaluit, NU",
    "Atlin, BC",
    "Avonlea, SK",
    "Macoun, SK",
    "Saint-jean-port-joli, QC",
    "Dapp, AB",
    "Beechy, SK",
    "Grenfell, SK",
    "Wiseton, SK",
    "Kagawong, ON",
    "Verner, ON",
    "Kapuskasing, ON",
    "Cobalt, ON",
    "Webbwood, ON",
    "Disraeli, QC",
    "Shipshaw, QC",
    "Whaletown, BC",
    "Mactier, ON",
    "Noelville, ON",
    "Elmvale, ON",
    "Sangudo, AB",
    "Neilburg, SK",
    "Preeceville, SK",
    "Rosetown, SK",
    "Naicam, SK",
    "Macklin, SK",
    "Lefroy, ON",
    "Pefferlaw, ON",
    "Minaki, ON",
    "Carseland, AB",
    "Blackie, AB",
    "Hespeler, ON",
    "Cap-rouge, QC",
    "Saint-jacques, QC",
    "Blackfalds, AB",
    "Coaldale, AB",
    "Balcarres, SK",
    "Kerrobert, SK",
    "Eston, SK",
    "Herschel, SK",
    "Luseland, SK",
    "Kennetcook, NS",
    "Consort, AB",
    "Vauxhall, AB",
    "Armstrong, BC",
    "Lipton, SK",
    "Saint-louis-de-terrebonne, QC",
    "Bonaventure, QC",
    "Amqui, QC",
    "Sainte-anne-des-monts, QC",
    "Jarvie, AB",
    "Hawkestone, ON",
    "Barachois, QC",
    "Gander, NL",
    "Campbellton, NB",
    "Westbourne, MB",
    "Gimli, MB",
    "Rorketon, MB",
    "Rossburn, MB",
    "Beauséjour, MB",
    "Wabana, NL",
    "Presque, NL",
    "Burin, NL",
    "Oderin, NL",
    "Boswarlos, NL",
    "Makkovik, NL",
    "Leader, SK",
    "Domremy, SK",
    "Wawota, SK",
    "Wabush, NL",
    "Tracadie, NB",
    "Glassville, NB",
    "Rexton, NB",
    "Boiestown, NB",
    "Dosquet, QC",
    "Saint-prosper, QC",
    "Borden-carleton, PE",
    "Stellarton, NS",
    "Rustico, PE",
    "Saint-honoré, QC",
    "Eastmain, QC",
    "Notre-dame-du-laus, QC",
    "Margaree, NS",
    "Ucluelet, BC",
    "Masset, BC",
    "Mabou, NS",
    "Finmoore, BC",
    "Rossland, BC",
    "Petitcodiac, NB",
    "Bowden, AB",
    "Aiyansh, BC",
    "Killam, AB",
    "Daysland, AB",
    "Veteran, AB",
    "Milden, SK",
    "Netherhill, SK",
    "Shamattawa, MB",
    "Pukatawagan, MB",
    "Nakina, ON",
    "Sayward, BC",
    "Bélanger, SK",
    "Leinan, SK",
    "Debert, NS",
    "Doaktown, NB",
    "Foremost, AB",
    "Sointula, BC",
    "Keatley, SK",
    "Magnetawan, ON",
    "Tilley, AB",
    "Burgeo, NL",
    "Saint-raymond, QC",
    "Drumbo, ON",
    "Kugluktuk, NU",
    "Resolute, NU",
    "Boissevain, MB",
    "Saint-jean-de-dieu, QC",
    "Flesherton, ON",
    "Yarker, ON",
    "Thamesville, ON",
    "Markstay, ON",
    "Saint-jude, QC",
    "Procter, BC",
    "Dundurn, SK",
    "Elrose, SK",
    "Silton, SK",
    "Harptree, SK",
    "Saint-malachie, QC",
    "Chipman, NB",
    "Oakburn, MB",
    "Carmanville, NL",
    "Bellburns, NL",
    "Colinet, NL",
    "Arcola, SK",
    "Duparquet, QC",
    "Guigues, QC",
    "Tlell, BC",
    "Tatamagouche, NS",
    "Bowser, BC",
    "Joussard, AB",
    "Linière, QC",
    "Beachberg, ON",
    "Edzo, NT",
    "Normandville, AB",
    "Meskanaw, SK",
    "Hurkett, ON",
    "Mundare, AB",
    "Deer, MB",
    "Kelfield, SK",
    "Cabri, SK",
    "Waskatenau, AB",
    "Normandeau, AB",
    "Eyebrow, SK",
    "Horsefly, BC",
    "Thorhild, AB",
    "Saint-tite, QC",
    "Saint-philippe-de-laprairie, QC",
    "Mattice, ON",
    "Gracefield, QC",
    "Radisson, QC",
    "Alluvia, BC",
    "Laval-ouest, QC",
    "Gitwinksihlkw, BC",
    "Asquith, SK",
    "Saint-siméon, QC",
    "Glacier, BC",
    "Armit, SK",
    "Pinantan, BC",
    "Sainte-emelie-de-l'energie, QC",
    "Arthabaska, QC",
    "Winnipegosis, MB",
    "Emsdale, ON",
    "Manotick, ON",
    "Saanichton, BC",
    "Lasalle, QC",
    "Boisbriand, QC",
    "Mackenzie, BC",
    "Aldergrove, BC",
    "Maskinongé, QC",
    "Innisfil, ON",
    "Tring-jonction, QC",
    "Westbank, BC",
    "Sundridge, ON",
    "Vananda, BC",
    "Clayhurst, BC",
    "Strathmore, AB",
    "Tobermory, ON",
    "Caroline, AB",
    "Sainte-monique, QC",
    "Ignace, ON",
    "Maxville, ON",
    "Saint-prime, QC",
    "Skead, ON",
    "Debden, SK",
    "Glenboro, MB",
    "Cascapedia, QC",
    "Rivière-au-tonnerre, QC",
    "Saint-pamphile, QC",
    "Moisie, QC",
    "Trois-rivieres, QC",
    "Cote-saint-luc, QC",
    "Levis, QC",
    "Chateauguay, QC",
    "Sainte-therese, QC",
    "Montreal-nord, QC",
    "Jonquiere, QC",
    "Riviere-du-loup, QC",
    "Saint-jerome, QC",
    "Montreal-est, QC",
    "Sept-iles, QC",
    "Ile-perrot, QC",
    "Saint-remi, QC",
    "Becancour, QC",
    "Rosemere, QC",
    "Riviere-des-prairies, QC",
    "Saint-felicien, QC",
    "Sainte-cecile-de-masham, QC",
    "Sainte-adele, QC",
    "Gaspe, QC",
    "Vercheres, QC",
    "Sainte-therese-de-blainville, QC",
    "Clericy, QC",
    "Hebertville, QC",
    "Saint-honore, QC",
    "Liniere, QC",
    "Saint-simeon, QC",
    "Maskinonge, QC",
    "Riviere-au-tonnerre, QC",
    "Id, AB",
    "Grande Prairie, AB",
    "Medicine Hat, AB",
    "Red Deer, AB",
    "Id, BC",
    "Kootenay, BC",
    "Prince George, BC",
    "Richmond, BC",
    "Id, MB",
    "Thompson, MB",
    "Id, NB",
    "Edmunston, NB",
    "Saint John, NB",
    "Id, NT",
    "Hay River, NT",
    "Id, NS",
    "Annapolis Royal, NS",
    "Bridgewater, NS",
    "Dartmouth, NS",
    "New Glasgow, NS",
    "Sydney, NS",
    "Yarmouth, NS",
    "Id, ON",
    "Burlington, ON",
    "Cambridge, ON",
    "Chatham, ON",
    "Don Mills, ON",
    "Durham, ON",
    "North Bay, ON",
    "North London, ON",
    "North Whitby, ON",
    "Owen Sound, ON",
    "Peterborough, ON",
    "Richmond Hill, ON",
    "Sault Ste. Marie, ON",
    "St. Catharines, ON",
    "St. Thomas, ON",
    "Thunder Bay, ON",
    "Toronto - Gta, ON",
    "Waterloo, ON",
    "Willowdale, ON",
    "Woodbridge, ON",
    "Id, PE",
    "Id, QC",
    "Cote-nord, QC",
    "Grand Portage, QC",
    "Hull, QC",
    "Lachenaie, QC",
    "Lanaudiere, QC",
    "Laurentians, QC",
    "Rouyn-noranda, QC",
    "Saint Jean, QC",
    "Saint Laurent, QC",
    "Saint-jean Sur Richelieu, QC",
    "Sainte-julie, QC",
    "Sept-isles, QC",
    "St Romuald-qc, QC",
    "St.-hyacinthe, QC",
    "Ste Foy, QC",
    "Id, SK",
    "Id, NL",
    "Id, NU",
    "Quebec City, QC",
    "Id, YT",
    "Ottawa (home Office), ON",
    "4000-toronto Eaton Centre, ON",
    "4001 - Sherway Gardens, ON",
    "4002-yorkdale Shopping Centre, ON",
    "4100-yorkdale Shopping Center, ON",
    "4102 - Toronto Eaton Centre, ON",
    "4104 - Lime Ridge Mall, ON",
    "Vancouver Technology Centre, BC",
    "Hemlo, ON",
    "Toronto- Aviation, ON",
    "Albright, AB",
    "Beiseker, AB",
    "Burdett, AB",
    "Chancellor, AB",
    "De Winton, AB",
    "Equity, AB",
    "Ervick, AB",
    "Fairview, AB",
    "Grimshaw, AB",
    "High River, AB",
    "Manning, AB",
    "Marwayne, AB",
    "Mclennan, AB",
    "Olds, AB",
    "Peace River, AB",
    "Rycroft, AB",
    "Spruce Grove, AB",
    "Vegreville, AB",
    "Vermilion, AB",
    "Viking, AB",
    "Fort St. John, BC",
    "Altona, MB",
    "Brandon, MB",
    "Carberry, MB",
    "Carman, MB",
    "Dauphin, MB",
    "Elm Creek, MB",
    "Elva, MB",
    "Morden, MB",
    "Morris, MB",
    "Nesbitt, MB",
    "Oakner, MB",
    "Plumas, MB",
    "Roblin, MB",
    "St. Boniface, MB",
    "Swan River, MB",
    "Sussex, NB",
    "Addison, ON",
    "Arkona, ON",
    "Clinton, ON",
    "Courtland, ON",
    "Glencoe, ON",
    "Greenway, ON",
    "Harriston, ON",
    "Harrow, ON",
    "Jarvis, ON",
    "Kerwood, ON",
    "Melbourne, ON",
    "Mt. Albert, ON",
    "Mt. Elgin, ON",
    "Palmerston, ON",
    "Princeton, ON",
    "Shakespeare, ON",
    "Shetland, ON",
    "Springford, ON",
    "Staples, ON",
    "Talbotville, ON",
    "Tilbury, ON",
    "Waterford, ON",
    "Woodstock, ON",
    "Chambly, QC",
    "Saint Hubert, QC",
    "Saint Romuald, QC",
    "St.- Valerien, QC",
    "Aberdeen, SK",
    "Belle Plaine, SK",
    "Biggar, SK",
    "Birch Hills, SK",
    "Canora, SK",
    "Canwood, SK",
    "Clavet, SK",
    "Colonsay, SK",
    "Congress, SK",
    "Craik, SK",
    "Cudworth, SK",
    "Cutknife, SK",
    "Davidson, SK",
    "Esterhazy, SK",
    "Humboldt, SK",
    "Ituna, SK",
    "Langbank, SK",
    "Leross, SK",
    "Marsden, SK",
    "Moose Jaw, SK",
    "Moosomin, SK",
    "Nicklen Siding, SK",
    "North Battleford, SK",
    "Raymore, SK",
    "Rowatt, SK",
    "Swift Current, SK",
    "Unity, SK",
    "Wynyard, SK",
    "Beaverlodge, AB",
    "Berwyn, AB",
    "Blairmore, AB",
    "Boyle, AB",
    "Brooks, AB",
    "Chestermere, AB",
    "Claresholm, AB",
    "Cochrane, AB",
    "Cold Lake, AB",
    "Crossfield, AB",
    "Delia, AB",
    "Eckville, AB",
    "Fort Macleod, AB",
    "Fort Mcmurray, AB",
    "Fort Saskatchewan, AB",
    "Fox Creek, AB",
    "Grande Cache, AB",
    "Hardisty, AB",
    "High Level, AB",
    "Jasper, AB",
    "Lac La Biche, AB",
    "Lacombe, AB",
    "Lamont, AB",
    "Milk River, AB",
    "Nanton, AB",
    "Okotoks, AB",
    "Pincher Creek, AB",
    "Provost, AB",
    "Redwater, AB",
    "Rocky Mountain House, AB",
    "Rockyford, AB",
    "Saint Paul, AB",
    "Sherwood Park, AB",
    "Smoky Lake, AB",
    "St. Albert, AB",
    "Stettler, AB",
    "Stony Plain, AB",
    "Sylvan Lake, AB",
    "Taber, AB",
    "Vulcan, AB",
    "Warner, AB",
    "100 Mile House, BC",
    "Burns Lake, BC",
    "Campbell River, BC",
    "Chetwynd, BC",
    "Dawson Creek, BC",
    "Fort Nelson, BC",
    "Fort Saint James, BC",
    "Fort Saint John, BC",
    "Fraser Lake, BC",
    "Gibsons, BC",
    "Golden, BC",
    "Grand Forks, BC",
    "Hope, BC",
    "Keremeos, BC",
    "Lillooet, BC",
    "Logan Lake, BC",
    "Maple Ridge, BC",
    "Merritt, BC",
    "Mill Bay, BC",
    "Mission, BC",
    "Nakusp, BC",
    "Nelson, BC",
    "New Westminster, BC",
    "North Vancouver, BC",
    "Oliver, BC",
    "Osoyoos, BC",
    "Pitt Meadows, BC",
    "Port Alberni, BC",
    "Port Coquitlam, BC",
    "Port Hardy, BC",
    "Port Mcneill, BC",
    "Powell River, BC",
    "Prince Rupert, BC",
    "Princeton, BC",
    "Qualicum Beach, BC",
    "Revelstoke, BC",
    "Salmon Arm, BC",
    "Salt Spring Island, BC",
    "Sechelt, BC",
    "Sidney, BC",
    "Sooke, BC",
    "Sparwood, BC",
    "Stewart, BC",
    "Summerland, BC",
    "Trail, BC",
    "West Vancouver, BC",
    "White Rock, BC",
    "Williams Lake, BC",
    "Winfield, BC",
    "Arborg, MB",
    "Ashern, MB",
    "Dominion City, MB",
    "Elkhorn, MB",
    "Fisher Branch, MB",
    "Flin Flon, MB",
    "Gilbert Plains, MB",
    "Grandview, MB",
    "Holland, MB",
    "Killarney, MB",
    "Leaf Rapids, MB",
    "Lundar, MB",
    "Miami, MB",
    "Neepawa, MB",
    "Portage La Prairie, MB",
    "Selkirk, MB",
    "Steinbach, MB",
    "Stonewall, MB",
    "The Pas, MB",
    "Treherne, MB",
    "Bathurst, NB",
    "Fairvale, NB",
    "Miramichi, NB",
    "Nackawic, NB",
    "Newcastle, NB",
    "Riverview, NB",
    "Rothesay, NB",
    "Saint Stephen, NB",
    "Salisbury, NB",
    "Woodstock, NB",
    "Clarenville, NL",
    "Corner Brook, NL",
    "Grand Falls-windsor, NL",
    "Labrador City, NL",
    "Lewisporte, NL",
    "Mount Pearl, NL",
    "St. John's, NL",
    "Fort Simpson, NT",
    "Norman Wells, NT",
    "Amherst, NS",
    "Antigonish, NS",
    "Barrington Passage, NS",
    "Bedford, NS",
    "Digby, NS",
    "Glace Bay, NS",
    "Greenwood, NS",
    "Kingston, NS",
    "Lower Sackville, NS",
    "Lunenburg, NS",
    "New Minas, NS",
    "Parrsboro, NS",
    "Sackville, NS",
    "Shelburne, NS",
    "Springhill, NS",
    "Sydney River, NS",
    "Truro, NS",
    "Windsor, NS",
    "Rankin Inlet, NU",
    "Acton, ON",
    "Ailsa Craig, ON",
    "Aurora, ON",
    "Aylmer, ON",
    "Ayr, ON",
    "Beaverton, ON",
    "Binbrook, ON",
    "Blenheim, ON",
    "Bloomfield, ON",
    "Blyth, ON",
    "Bobcaygeon, ON",
    "Bolton, ON",
    "Bradford, ON",
    "Brechin, ON",
    "Bridgenorth, ON",
    "Brighton, ON",
    "Brooklin, ON",
    "Brussels, ON",
    "Burford, ON",
    "Caledon East, ON",
    "Caledonia, ON",
    "Capreol, ON",
    "Carleton Place, ON",
    "Cayuga, ON",
    "Claremont, ON",
    "Coboconk, ON",
    "Concord, ON",
    "Cornwall, ON",
    "Cottam, ON",
    "Delhi, ON",
    "Dresden, ON",
    "Dundalk, ON",
    "Dundas, ON",
    "East Gwillimbury, ON",
    "Elliot Lake, ON",
    "Embrun, ON",
    "Emo, ON",
    "Essex, ON",
    "Exeter, ON",
    "Fenelon Falls, ON",
    "Forest, ON",
    "Fort Erie, ON",
    "Fort Frances, ON",
    "Georgetown, ON",
    "Gloucester, ON",
    "Goderich, ON",
    "Grimsby, ON",
    "Hannon, ON",
    "Hanover, ON",
    "Hensall, ON",
    "Huntsville, ON",
    "Ilderton, ON",
    "Kenora, ON",
    "Keswick, ON",
    "Killaloe Station, ON",
    "Kincardine, ON",
    "King City, ON",
    "Kingsville, ON",
    "Kirkland Lake, ON",
    "La Salle, ON",
    "Lakefield, ON",
    "Langton, ON",
    "Listowel, ON",
    "Manitouwadge, ON",
    "Maple, ON",
    "Matheson, ON",
    "Midland, ON",
    "Milverton, ON",
    "Minden, ON",
    "Mitchell, ON",
    "Monkton, ON",
    "New Hamburg, ON",
    "New Liskeard, ON",
    "Newcastle, ON",
    "Niagara Falls, ON",
    "Niagara On The Lake, ON",
    "Nobleton, ON",
    "North York, ON",
    "Norwich, ON",
    "Orleans, ON",
    "Orono, ON",
    "Paris, ON",
    "Parkhill, ON",
    "Parry Sound, ON",
    "Pembroke, ON",
    "Perth, ON",
    "Petrolia, ON",
    "Picton, ON",
    "Plattsville, ON",
    "Port Colborne, ON",
    "Port Credit, ON",
    "Port Elgin, ON",
    "Port Hope, ON",
    "Port Perry, ON",
    "Port Rowan, ON",
    "Rainy River, ON",
    "Red Lake, ON",
    "Richmond, ON",
    "Ridgeway, ON",
    "Saint Clements, ON",
    "Schomberg, ON",
    "Seaforth, ON",
    "Selkirk, ON",
    "Shedden, ON",
    "Sioux Lookout, ON",
    "Smiths Falls, ON",
    "Smithville, ON",
    "South Porcupine, ON",
    "Southampton, ON",
    "Stoney Creek, ON",
    "Sunderland, ON",
    "Tamworth, ON",
    "Terrace Bay, ON",
    "Thedford, ON",
    "Tottenham, ON",
    "Trenton, ON",
    "Tweed, ON",
    "Unionville, ON",
    "Uxbridge, ON",
    "Val Caron, ON",
    "Vaughan, ON",
    "Vineland, ON",
    "Wallaceburg, ON",
    "Wasaga Beach, ON",
    "Wellesley, ON",
    "Wingham, ON",
    "Yarmouth, ON",
    "Alberton, PE",
    "Cornwall, PE",
    "Montague, PE",
    "Murray River, PE",
    "Souris, PE",
    "Amos, QC",
    "Ayer's Cliff, QC",
    "Bedford, QC",
    "Bromont, QC",
    "Chapais, QC",
    "Chibougamau, QC",
    "Chisasibi, QC",
    "Danville, QC",
    "East Angus, QC",
    "Eastmain (james Bay), QC",
    "Farnham, QC",
    "Grand-mere, QC",
    "Havre-saint-pierre, QC",
    "Hemmingford, QC",
    "Howick, QC",
    "Huntingdon, QC",
    "Kirkland, QC",
    "Knowlton, QC",
    "La Prairie, QC",
    "La Sarre, QC",
    "Mansonville, QC",
    "Mascouche, QC",
    "Port-cartier, QC",
    "Richmond, QC",
    "Saint-bruno, QC",
    "Saint-chrysostome, QC",
    "Saint-ferdinand, QC",
    "Saint-lambert, QC",
    "Saint-leonard, QC",
    "Sorel-tracy, QC",
    "St-eustache, QC",
    "St-georges, QC",
    "St-jean-sur-richelieu, QC",
    "Stanstead, QC",
    "Ste-therese-de-blainville, QC",
    "Sutton, QC",
    "Thetford Mines, QC",
    "Vaudreuil-dorion, QC",
    "Waterloo, QC",
    "Waterville, QC",
    "Windsor, QC",
    "Big River, SK",
    "Blaine Lake, SK",
    "Carlyle, SK",
    "Central Butte, SK",
    "Coronach, SK",
    "Cowessess, SK",
    "Dinsmore, SK",
    "Fort Qu'appelle, SK",
    "Hafford, SK",
    "Kelvington, SK",
    "La Ronge, SK",
    "Laronge, SK",
    "Lloydminster, SK",
    "Loon Lake, SK",
    "Lucky Lake, SK",
    "Maidstone, SK",
    "Mankota, SK",
    "Maple Creek, SK",
    "Meadow Lake, SK",
    "Milestone, SK",
    "Mossbank, SK",
    "Norquay, SK",
    "Prince Albert, SK",
    "Radisson, SK",
    "Radville, SK",
    "Redvers, SK",
    "Rosthern, SK",
    "Rouleau, SK",
    "Saint Walburg, SK",
    "Stoughton, SK",
    "Wadena, SK",
    "Watson, SK",
    "Yellow Grass, SK",
    "Dawson, YT",
    "Watson Lake, YT",
    "Saint John's, NL",
    "Bainsville, ON",
    "Brighton_s, ON",
    "Dutton, ON",
    "Ingleside, ON",
    "Mallorytown North, ON",
    "Mallorytown South, ON",
    "Morrisburg, ON",
    "Odessa, ON",
    "West Lorne, ON",
    "St-laurent, QC",
    "Calg Northgate, AB",
    "Llodyminister, AB",
    "Slave Lake, AB",
    "Courtney, BC",
    "Sardis, BC",
    "Wesbank, BC",
    "Stienbach, MB",
    "Grands Falls, NB",
    "St. Basile, NB",
    "Cornerbrook, NL",
    "Kenmount, NL",
    "Cookville, NS",
    "Coburg, ON",
    "Cumberland, ON",
    "Hawesbury, ON",
    "Leamingont, ON",
    "Ottowa, ON",
    "Rockland, ON",
    "Sault Ste Marie, ON",
    "Smithsfa, ON",
    "Tillsonberg, ON",
    "Bleury, QC",
    "Cote St-luc, QC",
    "Faubourg, QC",
    "Greenfield Park, QC",
    "Pointe Claire, QC",
    "Saint Hyacinthe, QC",
    "Saint Leonard, QC",
    "Saint-georges, QC",
    "Sainte Foy, QC",
    "Sept Iles, QC",
    "St Eustache, QC",
    "St. Bruno, QC",
    "St. Jerome, QC",
    "Trois Rivieres, QC",
    "Cambridge Bay, NU",
    "Hope Bay, NU",
    "High Prairie, AB",
    "St. Paul, AB",
    "Cariboo, BC",
    "Chilcotin, BC",
    "Grand Rapids, MB",
    "Bonavista, NL",
    "Churchill Falls, NL",
    "Goose Bay, NL",
    "Grand Falls, NL",
    "St. Anthony, NL",
    "Inverness, NS",
    "Louisbourg, NS",
    "Cavendish, PE",
    "O'leary, PE",
    "La Tuque, QC",
    "Saguenay, QC",
    "Salaberry De Valleyfield, QC",
    "Schefferville, QC",
    "Thetford-mines, QC",
    "Ville St. Laurent, QC",
    "Iroquois Falls, ON",
    "Amos (abitibi), QC",
    "Charlevoix, QC",
    "Chateau-richer, QC",
    "Clermont, QC",
    "Comtois, QC",
    "Dolbeau-mistassini, QC",
    "Girardville, QC",
    "La Dore, QC",
    "Larouche, QC",
    "Laterriere, QC",
    "Lebel-sur-quevillon, QC",
    "Manseau, QC",
    "Obedjiwan, QC",
    "Petit-saguenay, QC",
    "St-fulgence, QC",
    "St-felicien, QC",
    "St-hilarion, QC",
    "St-ludger-de-milot, QC",
    "St-prime, QC",
    "St-thomas-didyme, QC",
    "Brooklyn, NS",
    "Dayspring, NS",
    "Saint Catherines, ON",
    "St Catharines, ON",
    "Rocky View, AB",
    "St Bruno, QC",
    "Drayton Valley, AB",
    "Bella Coola, BC",
    "Crawford Bay, BC",
    "Mcbride, BC",
    "Whistler, BC",
    "Grand Falls, NB",
    "Marystown, NL",
    "Stephenville, NL",
    "Port Hawkesbury, NS",
    "Chatham-kent, ON",
    "Temiskaming Shores, ON",
    "Fermont, QC",
    "La Malbaie, QC",
    "La Pocatiere, QC",
    "La Vallee-du-richelieu, QC",
    "Lac-megantic, QC",
    "Marguerite-d'youville, QC",
    "Matawinie, QC",
    "Mont-laurier, QC",
    "New Carlisle, QC",
    "Roussillon, QC",
    "Therese-de Blainville, QC",
    "Iles-de-la-madeleine, QC",
    "St. Laurent, QC",
    "Matsqui, BC",
    "Beresford, NB",
    "Big River, NB",
    "Caraquet, NB",
    "Dieppe, NB",
    "Oromocto, NB",
    "St. Laurent, NL",
    "Liverpool, NS",
    "Smith Falls, ON",
    "St.thomas, ON",
    "Vanier, ON",
    "St-bruno, QC",
    "St-bruno-de-montarville, QC",
    "St-hubert, QC",
    "St-jerome, QC",
    "Ste-foy, QC",
    "Cape Breton, NS",
    "Windsor(on), ON",
    "Saint-colomban, QC",
    "St-lambertdelauzon, QC",
    "Verdun, QC",
    "Hanna, AB",
    "Innisfail, AB",
    "La Crete, AB",
    "Lloydminister, AB",
    "Valleyview, AB",
    "Cache Creek, BC",
    "Fort St James, BC",
    "Ganges, BC",
    "Houston, BC",
    "Kimberley, BC",
    "Queen Charlottes, BC",
    "Salt Spring, BC",
    "Barrhaven, ON",
    "Bellville, ON",
    "St. Catherines, ON",
    "Blanc-sablon, QC",
    "Carleton, QC",
    "Mont Royal, QC",
    "Mont-st-hilaire, QC",
    "St-elie D'orford, QC",
    "St-georges-de-beauce, QC",
    "St-henri-de-levis, QC",
    "St.lambert, QC",
    "St.laurent, QC",
    "St.omer, QC",
    "Ste-marie De Beauce, QC",
    "Ste-marie-de-beauce, QC",
    "New Brunswick, NB",
    "Coutts, AB",
    "Coastal, BC",
    "Fraser Valley, BC",
    "Emmerson, MB",
    "Harbourfront, ON",
    "Humber, ON",
    "Lansdowne, ON",
    "Ville St Laurent, QC",
    "Eastern Passage Halifax, NS",
    "Annacis Island, BC",
    "Cassidy, BC",
    "Juskatla, BC",
    "Lumby, BC",
    "Nanoose Bay, BC",
    "Okanagan Falls, BC",
    "Vavenby, BC",
    "Ear Falls, ON",
    "New Dundee, ON",
    "Nipigon, ON",
    "Sturgeon Falls, ON",
    "Wawa, ON",
    "St Augustin De Desmaures, QC",
    "St. Jean Chrysostyme, QC",
    "Carrot River, SK",
    "Hudson Bay, SK",
    "North Delta, BC",
    "Halton, ON",
    "Leeds, ON",
    "Ottawa/nepean, ON",
    "Weston, ON",
    "Castlegar (trail), BC",
    "Bathhurst, NB",
    "Mirimachi, NB",
    "Coldbrook, NS",
    "Ontario, ON",
    "Sault Saint Marie, ON",
    "Winsloe, PE",
    "Baie Comeau, QC",
    "Mont Laurier, QC",
    "Pointe-au-pere, QC",
    "St Antonin, QC",
    "St Georges, QC",
    "Alberta Field, AB",
    "British Columbia Field, BC",
    "Manitoba Field, MB",
    "Ontario Field, ON",
    "Yonge Street, ON",
    "Quebec Field, QC",
    "Grand Prairie, AB",
    "St Albert, AB",
    "Clearbrook, BC",
    "Pentiction, BC",
    "Port Moody, BC",
    "South Surrey, BC",
    "Alberta North, AB",
    "Alberta South, AB",
    "Alberta/manitoba, AB",
    "Calgary North, AB",
    "Calgary South, AB",
    "Edmonton North, AB",
    "Edmonton South, AB",
    "Fraser Valley, AB",
    "Bc/saskatchewan, BC",
    "Bc/yukon, BC",
    "Okanogan, BC",
    "Vancouver & Interior, BC",
    "Vancouver Centre, BC",
    "Vancouver City, BC",
    "Vancouver Island, BC",
    "Vancouver Island & North, BC",
    "Vancouver North, BC",
    "Victoria/vancouver Island, BC",
    "Manitoba/saskatchewan, MB",
    "Moncton, NL",
    "Dartmouth/sydney, NS",
    "Halifax/yarmouth, NS",
    "Ns North/cape Breton, NS",
    "Eastern Ontario, ON",
    "Hamilton/niagara, ON",
    "Kitchener/waterloo, ON",
    "London/windsor, ON",
    "Markham/peterborough, ON",
    "Meadowpine - Head Office, ON",
    "Mississauga/oakville, ON",
    "Newmarket/huntsville, ON",
    "Northeastern Ontario, ON",
    "Ontario Central, ON",
    "Ontario East, ON",
    "Ontario East/atlantic, ON",
    "Ontario West, ON",
    "Oshawa/peterborough, ON",
    "Ottawa East, ON",
    "Ottawa West, ON",
    "Ottawa/atlantic, ON",
    "Sw & Nw Ontario, ON",
    "Sw Ontario, ON",
    "Sw Ontario/manitoba, ON",
    "Sw Ontario/manitoba/saskatchewan, ON",
    "Toronto Central, ON",
    "Toronto East, ON",
    "Toronto East/north, ON",
    "Toronto East/ottawa/atlantic, ON",
    "Toronto North, ON",
    "Toronto West, ON",
    "Toronto West/sw Ontario, ON",
    "Pei/moncton, PE",
    "Laval/laurentian, QC",
    "Montreal Center, QC",
    "Montreal East & North, QC",
    "Montreal Ne, QC",
    "Montreal North, QC",
    "Quebec North, QC",
    "Quebec South, QC",
    "Rive Sud Montreal, QC",
    "South Shore, QC",
    "West Island, QC",
    "Alberta, AB",
    "Work From Home, AB",
    "British Columbia, BC",
    "Work From Home, BC",
    "Work From Home, MB",
    "Work From Home, NB",
    "Nova Scotia, NS",
    "Work From Home, NS",
    "Work From Home, ON",
    "Work From Home, QC",
    "Work From Home, SK",
    "Amex - For Internal Use Only, AB",
    "Amex - For Internal Use Only, BC",
    "Amex - For Internal Use Only, MB",
    "Amex - For Internal Use Only, NB",
    "Amex - For Internal Use Only, NT",
    "Amex - For Internal Use Only, NS",
    "Amex - For Internal Use Only, NU",
    "Amex - For Internal Use Only, ON",
    "Amex - For Internal Use Only, PE",
    "Amex - For Internal Use Only, QC",
    "Amex - For Internal Use Only, SK",
    "Amex - For Internal Use Only, YT",
    "Southport, MB",
    "Alberta - Virtual Office, AB",
    "British Columbia - Virtual Office, BC",
    "Manitoba - Virtual Office, MB",
    "New Brunswick - Virtual Office, NB",
    "Nova Scotia - Virtual Office, NS",
    "Ontario - Virtual Office, ON",
    "Prince Edward Island - Virtual Office, PE",
    "Quebec - Virtual Office, QC",
    "Saskatchewan - Virtual Office, SK",
    "Skymark, ON",
    "Toronto - Downsview, ON",
    "Toronto - Downtown, ON",
    "Bagotville, QC",
    "Montreal - Cote St-luc, QC",
    "Montreal - Dorval, QC",
    "Montreal - Downtown, QC",
    "Montreal - Lachine, QC",
    "Montreal St. Laurent, QC",
    "St-hilaire, QC",
    "City Not Specified, AB",
    "City Not Specified, BC",
    "City Not Specified, MB",
    "City Not Specified, NS",
    "City Not Specified, ON",
    "City Not Specified, QC",
    "Nw Edmonton, AB",
    "West St Paul, MB",
    "L'assumption, QC",
    "St Jean Sur Richelieu, QC",
    "Ekati Mines, NT",
    "Agincourt, ON",
    "Corunna, ON",
    "Home Canada, ON",
    "Kingston, QC",
    "Lapoctiere, QC",
    "St Laurent, QC",
    "Patricia Bay, BC",
    "Halifax - Enfield, NS",
    "Shearwater, NS",
    "Astra, ON",
    "Alouette, QC",
    "Winnipeg Mb, MB",
    "Markham Ontario, ON",
    "Toronto Ontario, ON",
    "St. Johns, NL",
    "Iroquois-falls, ON",
    "Slemon Park, PE",
    "Saint Jean Sur Richelieu, QC",
    "All, AB",
    "Suffield, AB",
    "All, BC",
    "All, MB",
    "Beausejour, MB",
    "All, NB",
    "All, NS",
    "All, ON",
    "Saint Catharines, ON",
    "All, PE",
    "All, QC",
    "All, SK",
    "Red Water, AB",
    "Swan Hill, AB",
    "Hornell Heights, ON",
    "Shelburne, ON",
    "St. Marys, ON",
    "Nicolet, QC",
    "St Hubert, QC",
    "Al - Work At Home, AB",
    "Bc - Work At Home, BC",
    "Ns - Work At Home, NS",
    "On - Work At Home, ON",
    "Qc - Work At Home, QC",
    "Sk - Work At Home, SK",
    "Calgary-ab, AB",
    "Hardisty-ab-can, AB",
    "Surrey - Bc, BC",
    "Brandon-mb, MB",
    "Grande Pointe-mb, MB",
    "Bath-on-can, ON",
    "Brampton-on, ON",
    "Caledonia - On, ON",
    "District Of Timiskaming - On, ON",
    "Englehart-on, ON",
    "Kingston-on, ON",
    "Maitland-on, ON",
    "Mississauga-on, ON",
    "Rexdale - On, ON",
    "Sarnia-on-can, ON",
    "Thorold - On, ON",
    "Toronto-on-can, ON",
    "Uxbridge-on-can, ON",
    "Chateauguay - Qc, QC",
    "Saskatoon-sk, SK",
    "Saslatoon-sk-can, SK",
    "Tuxford-sk, SK",
    "Watson-sk, SK",
    "Terra Cotta, ON",
    "Mount Royal, QC",
    "Banff, Banff Avenue, AB",
    "Calgary Hemming Hub, AB",
    "Calgary, 4th Street, AB",
    "Calgary, Chinook Centre, AB",
    "Calgary, Market Mall, AB",
    "Calgary, South Centre, AB",
    "Edmonton, Kingsway Mall, AB",
    "Edmonton, West Edmonton Mall, AB",
    "Edmonton, Whyte, AB",
    "Grande Prairie Pop Up Outlet, AB",
    "Hemming Operations Edmonton, AB",
    "Ivivva Calgary, Chinook Centre, AB",
    "Ivivva Calgary, Market Mall, AB",
    "Ivivva Edmonton, Southgate Mall, AB",
    "Ivivva Edmonton, West Edmonton Mall, AB",
    "Burnaby, Distribution Centre Canada, BC",
    "Burnaby, Factory Outlet, BC",
    "Burnaby, Guest Education Centre (gec), BC",
    "Burnaby, Metrotown, BC",
    "Coquitlam, Coquitlam Centre, BC",
    "Ivivva Vancouver, West 4th, BC",
    "Ivivva, Park Royal, BC",
    "Kelowna, Bernard, BC",
    "Lab Vancouver, BC",
    "Store Support Centre, BC",
    "Vancouver Hemming Hub, BC",
    "Vancouver, Kitsilano, BC",
    "Vancouver, Oakridge, BC",
    "Vancouver, Robson, BC",
    "Vancouver, Warehouse Sale, BC",
    "Victoria, Johnson, BC",
    "West Vancouver, Park Royal, BC",
    "Whistler, Mountain, BC",
    "Ivivva Polo Park, Winnipeg, MB",
    "Winnipeg, Polo Park, MB",
    "Hemming Operations Toronto, ON",
    "Ivivva Oakville, ON",
    "Ivivva Toronto, Eaton Centre, ON",
    "Ivivva, Bayshore Pop Up, ON",
    "Ivivva, Yorkdale Pop Up, ON",
    "Kingston, Princess, ON",
    "London, Masonville, ON",
    "Newmarket, Upper Canada, ON",
    "Oakville Hemming Hub, ON",
    "Ontario, Oakville, ON",
    "Oshawa, Oshawa Centre, ON",
    "Ottawa Leadership Opportunities, ON",
    "Ottawa, Richmond Rd, ON",
    "Ottawa, Rideau Centre, ON",
    "Toronto Opportunities, ON",
    "Toronto, Cumberland, ON",
    "Toronto, Eaton Centre, ON",
    "Toronto, Promenade, ON",
    "Toronto, Queen Street, ON",
    "Toronto, Scarborough Town Centre, ON",
    "Toronto, Sherway Gardens, ON",
    "Toronto, Square One, ON",
    "Toronto, Vaughan Mills, ON",
    "Toronto, Yonge, ON",
    "Toronto, Yorkdale, ON",
    "Brossard, Quartier Dix 30, QC",
    "Montreal Leadership Opportunities, QC",
    "Montreal, Fairview, QC",
    "Montreal, Greene, QC",
    "Montreal, Hemming Hub, QC",
    "Montreal, St. Denis, QC",
    "Montreal, Ste. Catherine, QC",
    "Ivivva Saskatoon Pop Up, SK",
    "Regina, Cornwall Center, SK",
    "Enoch, AB",
    "Minett, ON",
    "Muskoka, ON",
    "Toronto, On, ON",
    "West Montreal, QC",
    "Calgary (north), AB",
    "Calgary (south), AB",
    "Edmonton (north), AB",
    "Edmonton (south), AB",
    "Vancouver (downtown), BC",
    "Vancouver (north Shore), BC",
    "Winnipeg (north), MB",
    "Winnipeg (south), MB",
    "St. John, NB",
    "Toronto (east), ON",
    "Toronto (north), ON",
    "Toronto (west), ON",
    "Montreal (west Island), QC",
    "Outaouais, QC",
    "Quebec East, QC",
    "South Shore (monteregie), QC",
    "Central Alberta, AB",
    "North West Alberta, AB",
    "Northern Alberta, AB",
    "South Alberta, AB",
    "Bc Interior, BC",
    "Greater Vancouver Area, BC",
    "Northern Bc, BC",
    "South Central Bc, BC",
    "Manitoba, MB",
    "Newfoundland And Labrador, NL",
    "Northwest Territories, NT",
    "Cape Breton Island, NS",
    "Mainland, NS",
    "Nunavut, NU",
    "Central Ontario, ON",
    "Greater Toronto Area, ON",
    "North Ontario, ON",
    "South East Ontario, ON",
    "South West Ontario, ON",
    "Prince Edward Island, PE",
    "Abitibi Temiscamingue, QC",
    "Bas Du Saint-laurent, QC",
    "Eastern Townships, QC",
    "Greater Montreal Area, QC",
    "La Mauricie, QC",
    "Monteregie, QC",
    "Saguenay-lac St-jean, QC",
    "Saskatchewan, SK",
    "Yukon Territories, YT",
    "Clairmont, AB",
    "Red Deer County, AB",
    "Greater Vancouver, BC",
    "Moncton Call Center, NB",
    "Waskada, MB",
    "Melita, MB",
    "Coleville, SK",
    "Marengo, SK",
    "Oxbow, SK",
    "Fort St John, BC",
    "Wabasca, AB",
    "Sedgewick, AB",
    "Alliance, AB",
    "Red Earth Creek, AB",
    "Swan Hills, AB",
    "Paradise, NL",
    "St. John's Metropolitan, NL",
    "St Johns Metrolpolit, NL",
    "Ft Saskatchewan, AB",
    "Scotford, AB",
    "St-antoine, QC",
    "Blackfalls, AB",
    "Amherst, NB",
    "Pedicodiac, NB",
    "Shediac, NB",
    "St John's, NL",
    "York, ON",
    "Trois-rivieres Quest, QC",
    "Kemano, BC",
    "Thunderbay, ON",
    "Can, BC",
    "Remote Can, BC",
    "Remote Canada #16029, BC",
    "Dsc Plant, ON",
    "Mississauga, On, ON",
    "Ontario, Canada, ON",
    "Richmond Hill, On, ON",
    "Temp, ON",
    "Coaticook, Canada, QC",
    "Kantech, Canada, QC",
    "Lachine, Pq, QC",
    "Mississauga, Quebec, Can, QC",
    "Vanier, QC",
    "Midale, SK",
    "Saskatoo, SK",
    "Yvr - Vancouver, BC",
    "Yyz - Toronto, ON",
    "Saint Albert, AB",
    "Florenceville, NB",
    "Ca-on_sudbury, ON",
    "Ca-on_whitby, ON",
    "Ca-on_windsor, ON",
    "Saint - Laurent, QC",
    "St.leon, MB",
    "Fermeuse, NL",
    "St Lawrence, NL",
    "Lower West Pubnico, NS",
    "Stoney Point, ON",
    "Tiverton, ON",
    "Elmira, PE",
    "North Cape, Tignish, PE",
    "West Cape, PE",
    "Murdochville, QC",
    "Calgary Ab, AB",
    "Edmonton Ab, AB",
    "Delta Bc, BC",
    "Langley Bc, BC",
    "Markham On, ON",
    "Mississauga On, ON",
    "Lachine Qc, QC",
    "Yeg - Edmonton, AB",
    "Yyc - Calgary, AB",
    "Ylw - Kelowna, BC",
    "Yyj - Victoria, BC",
    "Ywg - Winnipeg, MB",
    "Yqm - Moncton, NB",
    "Yyt - St. John's, NL",
    "Yhz - Halifax, NS",
    "Yhm - Hamilton, ON",
    "Yow - Ottawa, ON",
    "Yqt - Thunder Bay, ON",
    "Ytz - Toronto Island Airport, ON",
    "Yxu - London, ON",
    "Yqb - Quebec City, QC",
    "Ytm - La Macaza, QC",
    "Yul - Montreal, QC",
    "Yqr - Regina, SK",
    "Yxe - Saskatoon, SK",
    "Shanty Bay, ON",
    "Toronto, Gta, ON",
    "Rainbow Lake, AB",
    "Pendiction, BC",
    "Sarnia, BC",
    "Lincoln, NB",
    "Igaluit, NT",
    "Nancsivik, NT",
    "Nt, NT",
    "Enfield, NS",
    "London (on), ON",
    "Ste Catherine, ON",
    "Mont Joli, QC",
    "Rouyn, QC",
    "St Leonard, QC",
    "Val D'or, QC",
    "Yukon, YT",
    "Leaside, ON",
    "Kingsey Falls, QC",
    "Turtle Creek, NB",
    "Brockton, ON",
    "Nanticoke, ON",
    "Port Dover, ON",
    "Contrecoeur, QC",
    "Saint-romuald, QC",
    "Temiscaming, QC",
    "Other Locations/remote, QC",
    "Vancouver, QC",
    "Williamstown, ON",
    "Offsite/home, AB",
    "Offsite/home, BC",
    "Offsite/home, MB",
    "Offsite/home, NB",
    "Offsite/home, NL",
    "Offsite/home, NT",
    "Offsite/home, NS",
    "Offsite/home, NU",
    "Offsite/home, ON",
    "Offsite/home, PE",
    "Offsite/home, QC",
    "Offsite/home, SK",
    "Offsite/home, YT",
    "Baker Lake, NU",
    "Kiggavik, NU",
    "Cluff Lake, SK",
    "Mcclean Lake, SK",
    "Anzac, AB",
    "Bantry, AB",
    "Brazeau, AB",
    "Cessford, AB",
    "Elmworth, AB",
    "Empress, AB",
    "Fenn Big Valley, AB",
    "Goodfare, AB",
    "Hay River, AB",
    "Jenner, AB",
    "Morrin, AB",
    "Niton Junction, AB",
    "Peco, AB",
    "Red Earth, AB",
    "Rimbey, AB",
    "Sundre, AB",
    "Three Hills, AB",
    "Wembley, AB",
    "Fort Whyte, MB",
    "Alsask, SK",
    "Richardson, SK",
    "Etibicoke, ON",
    "British Columbia, AB",
    "Manitoba, AB",
    "New Brunswick, AB",
    "Newfoundland, AB",
    "Nova Scotia, AB",
    "Ontario, AB",
    "Prince Edward Island, AB",
    "Quebec, AB",
    "Saskatchewan, AB",
    "Alberta, BC",
    "Manitoba, BC",
    "New Brunswick, BC",
    "Newfoundland, BC",
    "Nova Scotia, BC",
    "Ontario, BC",
    "Prince Edward Island, BC",
    "Quebec, BC",
    "Saskatchewan, BC",
    "Alberta, MB",
    "British Columbia, MB",
    "New Brunswick, MB",
    "Newfoundland, MB",
    "Nova Scotia, MB",
    "Ontario, MB",
    "Prince Edward Island, MB",
    "Quebec, MB",
    "Saskatchewan, MB",
    "Alberta, NB",
    "British Columbia, NB",
    "Manitoba, NB",
    "Newfoundland, NB",
    "Nova Scotia, NB",
    "Ontario, NB",
    "Prince Edward Island, NB",
    "Quebec, NB",
    "Saskatchewan, NB",
    "Alberta, NS",
    "British Columbia, NS",
    "Manitoba, NS",
    "New Brunswick, NS",
    "Newfoundland, NS",
    "Ontario, NS",
    "Prince Edward Island, NS",
    "Quebec, NS",
    "Saskatchewan, NS",
    "Alberta, ON",
    "British Columbia, ON",
    "Manitoba, ON",
    "New Brunswick, ON",
    "Newfoundland, ON",
    "Nova Scotia, ON",
    "Prince Edward Island, ON",
    "Quebec, ON",
    "Saskatchewan, ON",
    "Alberta, PE",
    "British Columbia, PE",
    "Manitoba, PE",
    "New Brunswick, PE",
    "Newfoundland, PE",
    "Nova Scotia, PE",
    "Ontario, PE",
    "Quebec, PE",
    "Saskatchewan, PE",
    "Alberta, QC",
    "British Columbia, QC",
    "Manitoba, QC",
    "New Brunswick, QC",
    "Newfoundland, QC",
    "Nova Scotia, QC",
    "Ontario, QC",
    "Prince Edward Island, QC",
    "Saskatchewan, QC",
    "Alberta, SK",
    "British Columbia, SK",
    "Manitoba, SK",
    "New Brunswick, SK",
    "Newfoundland, SK",
    "Nova Scotia, SK",
    "Ontario, SK",
    "Prince Edward Island, SK",
    "Quebec, SK",
    "Home-based, AB",
    "Home-based, BC",
    "Home-based, MB",
    "Home-based, ON",
    "Home-based, QC",
    "Montreal (kirkland), QC",
    "Montreal (pointe-claire), QC",
    "Calgary Distribution Ctr(aaa5), AB",
    "Calgary Sales Office(9726), AB",
    "Ajax Plant [dupont](9701), ON",
    "Brampton, Chrysler Llc [2660](ca24), ON",
    "Concord-tarxien Automotive Group On Ca(ca09), ON",
    "Corunna(9801), ON",
    "Ford, Oakville, On, Ca(ca06), ON",
    "Honda, Alliston, On, Ca(ca07), ON",
    "Kingston Research(9747), ON",
    "Kingston(9741), ON",
    "Maitland(9751), ON",
    "Mississauga [dupont](9770), ON",
    "Mississauga [liqui-box](eybm), ON",
    "Plascoat, Mississauga, On, Ca(ca08), ON",
    "Rollstamp, Concord, On, Ca(ca11), ON",
    "Scarborough Dist Ctr, On Ca(c911), ON",
    "Tillsonburg-ddm Plastics(ca05), ON",
    "Toyota, Cambridge, On, Ca(ca10), ON",
    "Whitby, On Ca [dupont](9821), ON",
    "Whitby, On Ca [liqui-box](eyby), ON",
    "Montreal Sales Office(ca21), QC",
    "Pointe Claire Dist Ctr, Qc Ca(c901), QC",
    "Thetford Mines [dupont](ca02), QC",
    "Thetford Mines [granirex](eyaa), QC",
    "Red Cliff, AB",
    "Standard, AB",
    "Ft. Saskatchewan, AB",
    "Bristol, NB",
    "Chihuahua, NB",
    "Miramichi West, NB",
    "Richibucto, NB",
    "Bay Roberts, NL",
    "Deer Lake, NL",
    "Glovertown, NL",
    "Grand Bank, NL",
    "Harbour Breton, NL",
    "Port Au Choix, NL",
    "Port Aux Basques, NL",
    "Springdale, NL",
    "Wesleyville, NL",
    "North Sydney, NS",
    "Nuevo Casas Grandes, NS",
    "Port Hastings, NS",
    "Danforth, ON",
    "Espanola, ON",
    "St Thomas, ON",
    "Ancienne, QC",
    "Chandler, QC",
    "Dollard Des Ormeaux, QC",
    "Grand-llee (valleyfield), QC",
    "Ille Perrot, QC",
    "La Chute, QC",
    "La Salle, QC",
    "Montreal Nord Est, QC",
    "New Richmond, QC",
    "Pointe Aux Trembles, QC",
    "Sainte-constant, QC",
    "Sainte-dorothee-laval, QC",
    "Sainte-hubert, QC",
    "Sainte-leonard, QC",
    "Sainte-marie De Beuce, QC",
    "Vimont, QC",
    "Alert, NT",
    "Igaluit, NU",
    "Comeau, QC",
    "Bouctouche, NB",
    "Cap-pela(c), NB",
    "Clair, NB",
    "Fra(c)da(c)ricton, NB",
    "Grande-anse, NB",
    "Lama?que, NB",
    "Memramcook, NB",
    "Neguac, NB",
    "Norton, NB",
    "Petit-rocher, NB",
    "Rogersville, NB",
    "Shippagan, NB",
    "St-john, NB",
    "St-leonard, NB",
    "St-quentin, NB",
    "Tracadie-sheila, NB",
    "Central Gta, ON",
    "Eastern Gta, ON",
    "Northern Gta, ON",
    "Western Gta, ON",
    "Northern Ontario, ON",
    "Western Ontario, ON",
    "Abitibi-ta(c)miscamingue, QC",
    "Bas-st-laurent, QC",
    "Center Of Qua(c)bec, QC",
    "Chaudia?re-appalaches, QC",
    "Ca?te-nord, QC",
    "Gaspa(c)sie/a?les-de-la-madeleine, QC",
    "Lanaudia?re, QC",
    "Laval/north Shore, QC",
    "Mauricie, QC",
    "Montreal Island, QC",
    "Monta(c)ra(c)gie, QC",
    "North Of Quebec, QC",
    "Qua(c)bec City, QC",
    "Saguenay-lac-saint-jean, QC",
    "Quebec City / Levis, QC",
    "Montra(c)al, QC",
    "Lower Saint Lawrence, QC",
    "Central Qua(c)bec, QC",
    "Gaspa(c)sie - A?les-de-la-madeleine, QC",
    "Northern Qua(c)bec, QC",
    "Richelieu-yamaska, QC",
    "Greater Toronto Area (southern Ontario), ON",
    "Southwestern Ontario, ON",
    "Sydney, BC",
    "Atholville, NB",
    "Upper Tantallon, NS",
    "Chelmsford, ON",
    "Deep River, ON",
    "Hanmer, ON",
    "Niagara Region-st. Catharines, ON",
    "Niagara Region-welland, ON",
    "Prescott, ON",
    "Woolwich, ON",
    "Gaspa(c), QC",
    "La Pocatia?re, QC",
    "La(c)vis, QC",
    "Point Aux Trembles, QC",
    "Rivia?re-du-loup, QC",
    "St-constant, QC",
    "Ste-agathe-des-monts, QC",
    "Trois-rivia?res, QC",
    "Trois-rivia?res-ouest, QC",
    "Ville D'anjou, QC",
    "Vimont-laval, QC",
    "Cha?teauguay, QC",
    "Lac-ma(c)gantic, QC",
    "Saint-fa(c)licien, QC",
    "Saint-ja(c)ra?me, QC",
    "Sept-a?les, QC",
    "Missasauga, ON",
    "Halifax, Atlantic, NS",
    "Montri? 1/2 Al, QC",
    "Victoria Island, BC"
];
